# Generated by Django 3.2.9 on 2021-11-29 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MassSpectro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_sample', models.CharField(max_length=30)),
                ('counts', models.IntegerField()),
                ('file_spectrs', models.FileField(upload_to='Spectrs/%Y/%m/%d/')),
                ('table', models.FileField(upload_to='Table/%Y/%m/%d/')),
            ],
        ),
    ]
