# Generated by Django 3.2.9 on 2021-12-01 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='massspectro',
            old_name='file_spectrs',
            new_name='files',
        ),
        migrations.RenameField(
            model_name='massspectro',
            old_name='name_sample',
            new_name='sample_names',
        ),
    ]
